// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDljlnohhRFThC7_KCiHb-eDjcxozq1pE',
    appId: '1:152060009091:web:565e1489a48eb1bd8c19b6',
    messagingSenderId: '152060009091',
    projectId: 'instagram-bdb52',
    authDomain: 'instagram-bdb52.firebaseapp.com',
    storageBucket: 'instagram-bdb52.appspot.com',
    measurementId: 'G-5FT11SHDY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqHg0hv_HuJzWvyocgk_3h2Hp0wDkg5rw',
    appId: '1:152060009091:android:7709d9768142142f8c19b6',
    messagingSenderId: '152060009091',
    projectId: 'instagram-bdb52',
    storageBucket: 'instagram-bdb52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnNdwINehsB0dOuUREYQ9H2dj1ywdSnEs',
    appId: '1:152060009091:ios:cc439715048681918c19b6',
    messagingSenderId: '152060009091',
    projectId: 'instagram-bdb52',
    storageBucket: 'instagram-bdb52.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnNdwINehsB0dOuUREYQ9H2dj1ywdSnEs',
    appId: '1:152060009091:ios:cc439715048681918c19b6',
    messagingSenderId: '152060009091',
    projectId: 'instagram-bdb52',
    storageBucket: 'instagram-bdb52.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDljlnohhRFThC7_KCiHb-eDjcxozq1pE',
    appId: '1:152060009091:web:88903775c593b6098c19b6',
    messagingSenderId: '152060009091',
    projectId: 'instagram-bdb52',
    authDomain: 'instagram-bdb52.firebaseapp.com',
    storageBucket: 'instagram-bdb52.appspot.com',
    measurementId: 'G-446FK0CT1R',
  );
}
